### ISSUE TITLE
Type declaration issues

### ISSUE THREAD

**Issue by andrewparmet** [phax/ph-javacc-maven-plugin#3]
When using this version of the plugin the generated parser code does not compile. The ParserTokenManager declares a `private int curChar` when it should be a `char`. This bug does not exist with the original `javacc-maven-plugin`. I haven't dug deeply to figure out what causes this incompatibility, but maybe an upgrade to JavaCC 7.x would help fix this?

**Comment by phax** [comment]
The original `javacc-maven-plugin` uses JavaCC 5.0 which doesn't even have the `DumpStaticVarDeclarations.template` file. Also if I look at the official JavaCC 6.1.3 release, it is also `int`: https://github.com/javacc/javacc/blob/release_6_1_3/src/main/resources/templates/DumpStaticVarDeclarations.template#L13

And additionally `int` is a broader type than `char` so I don't see the problem here.
So I think you should adopt to `int`.
hth, Philip

**Comment by andrewparmet** [comment]
Ah, but the generated code does not compile! The ParserTokenManager has code that throws a  TokenMgrError, whose constructor takes a `char`, not an `int`. This is not merely an issue of personal preference. A code generator should generate code that compiles.

Also, I discovered it is possible to use the original `javacc-maven-plugin` with JavaCC 7.x with the following config:

```xml
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>javacc-maven-plugin</artifactId>
        <version>2.6</version>
        <executions>
          <execution>
            <goals>
              <goal>javacc</goal>
            </goals>
            <configuration>
              <outputDirectory>${basedir}/src/main/java/</outputDirectory>
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>net.java.dev.javacc</groupId>
            <artifactId>javacc</artifactId>
            <version>7.0.2</version>
          </dependency>
        </dependencies>
      </plugin>
```

**Comment by phax** [comment]
Okay - I checked with my output in ph-css and there it works fine....
Did you invoke an `mvn clean generate-source`???? Maybe the JavaCC code was not re-generated????
Do you have a class derived from the generated `*TokenManager` class??

This plugin has a slightly "fixed" version of 6.1.3 - that's why I integrated the JavaCC sources into the project. It was a mess at the time I integrated it and it is still difficult (having a build.xml and a pom.xml, weird folder structure...).

**Comment by andrewparmet** [comment]
Here's the commit that's broken: https://github.com/andrewparmet/mysql2h2-converter/commit/afd76c8fea4850ba5301639932dad2678c210625. If I run `mvn com.helger.maven:ph-javacc-maven-plugin:javacc` I hit the problem. I inherited the pom.xml, so the .jj file isn't in the default location and I"m not sure why the plugin isn't respecting the generate-sources goal.

**Comment by andrewparmet** [comment]
Solved by using the original JavaCC plugin as configured above.
